import csv, os

EVENTS = [
    dict(id=1,  year=2009, category="Grant",     subcategory="Statewide",         title="CPRIT Established - First Grants Awarded",                         authors="",                                   journal="",                           volume_issue_pages="",               institution="Statewide, Texas",                                  pmid="",            grant_id="RP_INITIAL",    grant_amount_usd=3000000000, description="Voters approved Prop 15 authorizing $3B for cancer research. BCM and MD Anderson liver researchers were early recipients, launching Texas's HCC infrastructure.", tags="CPRIT,policy,funding,statewide"),
    dict(id=2,  year=2011, category="Article",   subcategory="BCM",               title="Hepatocellular Carcinoma",                                          authors="El-Serag HB",                        journal="N Engl J Med",               volume_issue_pages="365:1118-1127",  institution="Baylor College of Medicine / Houston VA",           pmid="21992124",    grant_id="",              grant_amount_usd="",         description="Landmark global HCC review documenting the rapid rise of HCV-related HCC as the fastest-growing cause of US cancer deaths.",                                       tags="HCC,HCV,epidemiology,review"),
    dict(id=3,  year=2012, category="Article",   subcategory="Ramirez Lab",       title="HCC Incidence & Risk Factors in Texas Latinos",                     authors="Ramirez AG et al.",                  journal="PLoS One",                   volume_issue_pages="7(4):e35573",    institution="UTHSCSA / IHPR San Antonio",                        pmid="22530052",    grant_id="",              grant_amount_usd="",         description="First study documenting South Texas Latinos have the nation's highest HCC rates (10.6/100K). Identified obesity and diabetes as key modifiable risk factors.",    tags="HCC,Latino,disparities,Texas,epidemiology,UTHSCSA"),
    dict(id=4,  year=2012, category="Article",   subcategory="BCM",               title="Epidemiology of Viral Hepatitis and HCC",                           authors="El-Serag HB",                        journal="Gastroenterology",           volume_issue_pages="142(6):1264-1273",institution="Baylor College of Medicine",                        pmid="22537432",    grant_id="",              grant_amount_usd="",         description="Quantified population-attributable fraction of HBV/HCV in HCC; foundational for Texas public health interventions.",                                              tags="HCC,HBV,HCV,epidemiology,BCM"),
    dict(id=5,  year=2014, category="Article",   subcategory="Ramirez Lab",       title="HCC in Texas Latinos 1995-2010: An Update",                        authors="Ramirez AG et al.",                  journal="PLoS One",                   volume_issue_pages="9(6):e99365",    institution="UTHSCSA / IHPR San Antonio",                        pmid="24915432",    grant_id="",              grant_amount_usd="",         description="Confirmed TX Latino male/female HCC rates 3.1x and 4.0x higher than non-Hispanic Whites.",                                                                      tags="HCC,Latino,disparities,Texas,UTHSCSA"),
    dict(id=6,  year=2015, category="Grant",     subcategory="Multi-Institution", title="Texas HCC Consortium (THCCC) — CPRIT Launch",                       authors="El-Serag HB; Kanwal F (Multi-PI)",    journal="",                           volume_issue_pages="",               institution="BCM / VA / MD Anderson / UTSW / Parkland / UT San Antonio", pmid="", grant_id="RP150587",      grant_amount_usd=6000000,    description="CPRIT Multi-Investigator Award (RP150587) establishing the THCCC — now the largest ongoing prospective cohort of patients with cirrhosis in the nation, across 6 Texas centers.",  tags="CPRIT,THCCC,cohort,biomarkers,multi-institution,El-Serag,Kanwal"),
    dict(id=30, year=2016, category="Grant",     subcategory="UTHSCSA",           title="Clayton Foundation — HCC Biorepository & Treatment Research",      authors="Cigarroa FG; Sun L",                 journal="",                           volume_issue_pages="",               institution="UT Health San Antonio (UTHSCSA)",                   pmid="",            grant_id="CLAYTON_2016",  grant_amount_usd=1500000,    description="$300K/year for up to 5 years from the Clayton Foundation for Research. Develops an HCC biorepository and new treatment strategies; focused on the disproportionately high HCC burden in South Texas Hispanics.",      tags="Clayton Foundation,UTHSCSA,grant,HCC,Hispanic,biorepository,San Antonio"),
    dict(id=7,  year=2017, category="Article",   subcategory="Ramirez Lab",       title="Lifestyle & Clinical Correlates of HCC - Aflatoxin Study",         authors="Ramirez AG et al.",                  journal="Clin Gastroenterol Hepatol", volume_issue_pages="16(3):373-380",  institution="UTHSCSA / IHPR San Antonio",                        pmid="28344065",    grant_id="",              grant_amount_usd="",         description="First U.S. study linking aflatoxin exposure to HCC in a Latino-majority population. Cases had 6x higher odds of detectable aflatoxins in blood.",               tags="HCC,Latino,aflatoxin,risk factors,UTHSCSA"),
    dict(id=8,  year=2018, category="Article",   subcategory="UTSW",              title="AFP + Ultrasound for HCC Detection: Meta-Analysis",                 authors="Tzartzeva K, Obi J, Rich NE, Singal AG et al.",journal="Gastroenterology",           volume_issue_pages="154(6):1706-1718",institution="UT Southwestern Dallas",                            pmid="29425931",    grant_id="",              grant_amount_usd="",         description="32 studies: AFP + ultrasound improves HCC sensitivity to 63% vs 45% for ultrasound alone. Formed basis for updated AASLD surveillance guidelines.",              tags="HCC,AFP,surveillance,meta-analysis,AASLD,UTSW"),
    dict(id=9,  year=2018, category="Milestone", subcategory="Multi-Institution", title="THCCC Cohort - 2000+ Patients Enrolled",                            authors="",                                   journal="",                           volume_issue_pages="",               institution="BCM / UTSW / MD Anderson / UT San Antonio",         pmid="",            grant_id="",              grant_amount_usd="",         description="Semi-annual ultrasound, AFP, labs, and biospecimens collected across 5 Texas sites. One of the largest prospective HCC biomarker repositories in the US.",      tags="THCCC,cohort,milestone,biomarkers"),
    dict(id=10, year=2018, category="Article",   subcategory="Multi-Institution", title="Epidemiology and Management of HCC",                                authors="Singal AG; El-Serag HB et al.",      journal="Gastroenterology",           volume_issue_pages="154(6):1693-1704",institution="UT Southwestern / BCM",                             pmid="",            grant_id="",              grant_amount_usd="",         description="Comprehensive review of HCC risk stratification, surveillance, staging, and treatment. Addressed NAFLD/NASH-HCC epidemic and rising rates in Hispanic populations.", tags="HCC,NAFLD,NASH,epidemiology,review,UTSW,BCM"),
    dict(id=11, year=2019, category="Grant",     subcategory="BCM",               title="TeCH Center CAP Round 1",                                           authors="Multi-PI",                           journal="",                           volume_issue_pages="",               institution="BCM / MD Anderson Texas",                           pmid="",            grant_id="TeCH_CAP_R1",   grant_amount_usd=18000000,   description="CPRIT Collaborative Action Program (CAP) award — up to $18M — establishing the Texas Collaborative Center for HCC (TeCH) as the coordinating hub for statewide HCC research.",  tags="CPRIT,TeCH,BCM,multi-institution,collaborative,CAP"),
    dict(id=12, year=2019, category="Grant",     subcategory="BCM",               title="HCC Biomarker Validation - El-Serag",                              authors="El-Serag HB",                        journal="",                           volume_issue_pages="",               institution="BCM Houston",                                       pmid="",            grant_id="RP190641",      grant_amount_usd=3000000,    description="Biomarker validation grant for HCC early detection research within the THCCC cohort.",                                                                            tags="CPRIT,BCM,biomarkers,HCC,early detection"),
    dict(id=13, year=2019, category="Grant",     subcategory="MD Anderson",       title="Patient-Centered Liver Cancer Prevention - Hwang",                 authors="Hwang JP",                           journal="",                           volume_issue_pages="",               institution="MD Anderson Cancer Center",                         pmid="",            grant_id="MDA_HCC_2019",  grant_amount_usd=2460000,    description="Patient-centered liver cancer prevention initiative targeting at-risk populations at MD Anderson.",                                                               tags="CPRIT,MDA,prevention,HCC,patient-centered"),
    dict(id=14, year=2019, category="Article",   subcategory="Multi-Institution", title="Texas HCC Consortium (THCCC) Cohort Study Design",                  authors="Loo N; El-Serag HB; Singal AG et al.",journal="Am J Gastroenterol",       volume_issue_pages="114(3):530-532", institution="BCM / UTSW / MD Anderson / UT San Antonio",         pmid="30699099",    grant_id="",              grant_amount_usd="",         description="Describes the THCCC 5000-patient prospective cohort design and multi-center data collection protocol.",                                                          tags="THCCC,cohort,study design,BCM,UTSW,MDA"),
    dict(id=15, year=2019, category="Article",   subcategory="Ramirez Lab",       title="Metformin Modifies HCC Disparity in Diabetic Men",                  authors="Wang CP; Ramirez AG et al.",         journal="Cancer Med",                 volume_issue_pages="8(6):3206-3215", institution="UTHSCSA San Antonio (VA Study)",                    pmid="30993905",    grant_id="",              grant_amount_usd="",         description="In 84433 men with T2D, metformin was associated with reduced HCC risk with stronger effects in Hispanic and African American men.",                              tags="HCC,metformin,diabetes,disparities,Latino,UTHSCSA"),
    dict(id=16, year=2020, category="Grant",     subcategory="UTSW",              title="Cirrhosis Cohort Biomarker Surveillance - Singal",                  authors="Singal AG",                          journal="",                           volume_issue_pages="",               institution="UT Southwestern Dallas",                            pmid="",            grant_id="RP200537",      grant_amount_usd=2500000,    description="3000-patient cirrhosis cohort developing biomarker-based HCC surveillance algorithms.",                                                                          tags="CPRIT,UTSW,cirrhosis,surveillance,biomarkers"),
    dict(id=17, year=2020, category="Grant",     subcategory="BCM",               title="Genetic Epidemiology of HCC in Hispanics - Thrift",                authors="Thrift AP",                          journal="",                           volume_issue_pages="",               institution="BCM Houston",                                       pmid="",            grant_id="RP200554",      grant_amount_usd=2470000,    description="Genetic epidemiology of HCC in Hispanics; focused on PNPLA3 and TM6SF2 variants.",                                                                               tags="CPRIT,BCM,genetics,Hispanic,epidemiology,PNPLA3,TM6SF2"),
    dict(id=18, year=2020, category="Article",   subcategory="UTSW",              title="Epidemiology & Surveillance for HCC: New Trends",                   authors="Singal AG et al.",                   journal="J Hepatol",                  volume_issue_pages="72(2):250-261",  institution="UT Southwestern Dallas",                            pmid="31954490",    grant_id="",              grant_amount_usd="",         description="Documents shift from viral hepatitis to NAFLD/NASH as dominant HCC etiology; projects 122% increase in NAFLD-HCC by 2030.",                                     tags="HCC,NAFLD,NASH,epidemiology,surveillance,UTSW"),
    dict(id=19, year=2020, category="Article",   subcategory="Multi-Institution", title="AGA Update: HCC Surveillance in NAFLD",                             authors="Singal AG; El-Serag HB",             journal="Gastroenterology",           volume_issue_pages="158(7):1822-1830",institution="UT Southwestern / BCM",                             pmid="",            grant_id="",              grant_amount_usd="",         description="Joint AGA expert review on HCC screening in the rapidly growing NAFLD population. Addresses surveillance intervals and novel biomarkers.",                        tags="HCC,NAFLD,surveillance,AGA,review,UTSW,BCM"),
    dict(id=20, year=2022, category="Grant",     subcategory="UTHSCSA",           title="Community HCC Prevention at Safety-Net Clinics",                    authors="",                                   journal="",                           volume_issue_pages="",               institution="UT Health Texas",                                   pmid="",            grant_id="PP220022",      grant_amount_usd=1960000,    description="Community-based HCC prevention initiative at safety-net clinics targeting underserved Texas populations.",                                                       tags="CPRIT,UTHSCSA,prevention,community,safety-net,health equity"),
    dict(id=21, year=2022, category="Grant",     subcategory="BCM",               title="GALAD + AFP-L3 Biomarker Validation - El-Serag",                   authors="El-Serag HB",                        journal="",                           volume_issue_pages="",               institution="BCM Houston",                                       pmid="",            grant_id="RP220119",      grant_amount_usd=2000000,    description="Validation of GALAD score and AFP-L3 as early detection biomarkers within the THCCC cohort.",                                                                    tags="CPRIT,BCM,GALAD,AFP-L3,biomarkers,early detection"),
    dict(id=22, year=2022, category="Grant",     subcategory="Multi-Institution", title="TeCH Center CAP Round 2",                                           authors="Multi-PI",                           journal="",                           volume_issue_pages="",               institution="BCM / MD Anderson / UTSW / UTHealth",               pmid="",            grant_id="TeCH_CAP_R2",   grant_amount_usd=18000000,   description="TeCH Center renewal expanding NASH-HCC research and health equity initiatives across Texas institutions.",                                                        tags="CPRIT,TeCH,NASH,health equity,multi-institution"),
    dict(id=31, year=2022, category="Grant",     subcategory="Multi-Institution", title="NCI P01 — THCCC Five-Year Research Program",                        authors="El-Serag HB; Kanwal F (Multi-PI)",    journal="",                           volume_issue_pages="",               institution="BCM / VA / MD Anderson / UTSW / Parkland / UT San Antonio", pmid="", grant_id="P01CA263025",   grant_amount_usd=5500000,    description="NCI P01 CA263025 ($5.5M+, 5 years) funding five THCCC research projects: NAFLD risk factors, metabolic syndrome, circadian disruption, biomarker development, and randomized prevention trials.", tags="NCI,THCCC,P01,cohort,biomarkers,NAFLD,prevention,multi-institution"),
    dict(id=23, year=2022, category="Article",   subcategory="UTSW",              title="HCC Surveillance Improves Outcomes: Meta-Analysis",                 authors="Singal AG et al.",                   journal="J Hepatol",                  volume_issue_pages="77(1):128-139",  institution="UT Southwestern Dallas",                            pmid="35139400",    grant_id="",              grant_amount_usd="",         description="59 studies / 145396 patients: Surveillance yields 1.86x early-stage detection and 33% mortality reduction (HR 0.67).",                                           tags="HCC,surveillance,meta-analysis,outcomes,UTSW"),
    dict(id=24, year=2022, category="Article",   subcategory="Multi-Institution", title="The Texas Collaborative Center for HCC (TeCH)",                     authors="Harrison AC; El-Serag HB et al.",    journal="Front Oncol",                volume_issue_pages="",               institution="BCM / MD Anderson / UTSW / UTHealth",               pmid="36059708",    grant_id="",              grant_amount_usd="",         description="Describes TeCH's multi-institutional research, education, and advocacy framework targeting reduction of Texas liver cancer mortality by 2030.",                   tags="TeCH,BCM,UTSW,MDA,multi-institution,health equity"),
    dict(id=25, year=2023, category="Grant",     subcategory="TCH",               title="Predictive Biomarkers for Pediatric HCC - Lopez-Terrada",           authors="Lopez-Terrada D",                    journal="",                           volume_issue_pages="",               institution="Texas Children's Hospital",                         pmid="",            grant_id="TCH_HCC_2023",  grant_amount_usd=5980000,    description="Predictive biomarkers for pediatric HCC and hepatoblastoma at Texas Children's Hospital.",                                                                       tags="CPRIT,TCH,pediatric,hepatoblastoma,biomarkers"),
    dict(id=26, year=2023, category="Grant",     subcategory="UTSW",              title="Molecular Mechanisms of HCC Progression - Zhong",                  authors="Zhong",                              journal="",                           volume_issue_pages="",               institution="UT Southwestern Dallas",                            pmid="",            grant_id="UTSW_HCC_2023", grant_amount_usd=1050000,    description="Investigation of molecular mechanisms driving HCC progression and therapeutic targets.",                                                                          tags="CPRIT,UTSW,molecular biology,HCC,mechanisms"),
    dict(id=27, year=2023, category="Article",   subcategory="Multi-Institution", title="Prevention of HCC - White Paper",                                   authors="TeCH Consortium",                    journal="Hepatol Commun",             volume_issue_pages="",               institution="TeCH Multi-Institution Consortium",                 pmid="PMC10524305", grant_id="",              grant_amount_usd="",         description="Consensus recommendations covering HBV vaccination, HCV cure, metabolic intervention, and health equity strategies for Hispanic Texas communities.",              tags="TeCH,prevention,HBV,HCV,health equity,Hispanic,consensus"),
    dict(id=28, year=2024, category="Article",   subcategory="BCM",               title="HES v2.0 Outperforms GALAD for HCC Detection",                      authors="El-Serag HB; Jin M et al.",          journal="Hepatology",                 volume_issue_pages="",               institution="Baylor College of Medicine / THCCC Network",        pmid="",            grant_id="",              grant_amount_usd="",         description="Phase 3 biomarker evaluation: HES v2.0 (AFP + AFP-L3 + DCP + clinical variables) demonstrated superior sensitivity and specificity over GALAD for early HCC detection.", tags="HCC,HES,GALAD,biomarkers,AFP-L3,DCP,early detection,BCM"),
    dict(id=29, year=2025, category="Milestone", subcategory="Multi-Institution", title="CPRIT Surpasses $4B + NCI SPORE Designation",                        authors="",                                   journal="",                           volume_issue_pages="",               institution="UTSW / BCM / MD Anderson Texas",                    pmid="",            grant_id="",              grant_amount_usd=4000000000, description="CPRIT surpasses $4B total (~$59-77M to liver cancer). UT Southwestern receives the first Texas NCI SPORE for Liver Cancer with Singal, Yopp et al.",          tags="CPRIT,milestone,NCI,SPORE,UTSW,BCM,MDA"),
    dict(id=32, year=2019, category="Milestone", subcategory="Statewide",         title="CPRIT Discloses $46M+ Cumulative HCC Investment",                   authors="",                                   journal="",                           volume_issue_pages="",               institution="CPRIT / Statewide Texas",                           pmid="",            grant_id="",              grant_amount_usd=46000000,   description="CPRIT disclosed more than $46M invested in HCC academic research and prevention since 2010 — reflecting the policy impact of Texas researchers documenting the state's outsized liver cancer burden. Announced alongside the Liver Cancer Collaborative Action Program (CAP) launching the TeCH Center.",  tags="CPRIT,milestone,policy,HCC,statewide,$46M,CAP,TeCH"),
    dict(id=33, year=2021, category="Symposium", subcategory="Mays/UTHSCSA",      title="San Antonio Liver Cancer Symposium — Inaugural Virtual Edition",    authors="",                                   journal="",                           volume_issue_pages="",               institution="Mays Cancer Center, UT Health San Antonio",         pmid="",            grant_id="",              grant_amount_usd="",         description="First SALCS, held virtually October 1–2, 2021. Modeled after the San Antonio Breast Cancer Symposium. 50+ speakers from MD Anderson, Mayo Clinic, NCI, and Northwestern; covered HCC epidemiology, pre-clinical, translational, survivorship, and pediatric HCC. UTHSA presentation: [TBD].", tags="SALCS,symposium,Mays Cancer Center,UTHSCSA,liver cancer,inaugural,virtual,San Antonio"),
    dict(id=36, year=2022, category="Symposium", subcategory="Mays/UTHSCSA",      title="San Antonio Liver Cancer Symposium 2022",                           authors="Patel Arora S; Rauenzahn Cervantez S (Eds.)", journal="Ann Palliat Med", volume_issue_pages="13(4):747-748",  institution="Mays Cancer Center, UT Health San Antonio / Downtown San Antonio", pmid="38735687", grant_id="",             grant_amount_usd="",         description="Second SALCS, October 15–16, 2022, downtown San Antonio. Sessions: community liver cancer programs, personalized approaches for viral/non-viral HCC, current therapeutic landscape, and locoregional treatments (surgery, IR, transplant). Led to a special series in Annals of Palliative Medicine. UTHSA presentation: [TBD].", tags="SALCS,symposium,Mays Cancer Center,UTHSCSA,liver cancer,HCC,San Antonio,Ann Palliat Med"),
    dict(id=34, year=2023, category="Symposium", subcategory="Mays/UTHSCSA",      title="San Antonio Liver Cancer Symposium 2023",                           authors="",                                   journal="",                           volume_issue_pages="",               institution="Mays Cancer Center, UT Health San Antonio / Hilton San Antonio Hill Country", pmid="", grant_id="",              grant_amount_usd="",         description="Third SALCS, October 20–21, 2023, Hilton San Antonio Hill Country. Focus on HCC disparities, NAFLD-HCC, and community programs for at-risk Hispanic populations in South Texas. UTHSA presentation: [TBD].", tags="SALCS,symposium,Mays Cancer Center,UTHSCSA,liver cancer,NAFLD,Hispanic,San Antonio"),
    dict(id=37, year=2024, category="Symposium", subcategory="Mays/UTHSCSA",      title="San Antonio Liver Cancer Symposium 2024",                           authors="Patel Arora S; Fritze D (Co-Directors)", journal="",                          volume_issue_pages="",               institution="Mays Cancer Center, UT Health San Antonio / Hilton Palacio del Rio", pmid="", grant_id="",              grant_amount_usd="",         description="Fourth SALCS, October 11–12, 2024, Hilton Palacio del Rio, San Antonio. Sessions: pediatric liver cancer, future of HCC screening and surveillance, advances in surgery, transplantation, and interventional radiology, and caregiver support. UTHSA presentation: [TBD].", tags="SALCS,symposium,Mays Cancer Center,UTHSCSA,liver cancer,HCC,surveillance,San Antonio,2024"),
    dict(id=35, year=2025, category="Symposium", subcategory="Mays/UTHSCSA",      title="San Antonio Liver Cancer Symposium 2025",                           authors="Patel Arora S; Fritze D (Co-Chairs)",   journal="",                          volume_issue_pages="",               institution="Mays Cancer Center, UT Health San Antonio / Westin San Antonio North", pmid="", grant_id="",              grant_amount_usd="",         description="Fifth SALCS, October 9–11, 2025, Westin San Antonio North. Annual gathering of doctors, researchers, medical students, and patient advocates advancing liver cancer care in Texas. UTHSA presentation: [TBD].", tags="SALCS,symposium,Mays Cancer Center,UTHSCSA,liver cancer,HCC,San Antonio,2025"),
]

FIELDS = ['id','year','category','subcategory','title','authors','journal','volume_issue_pages','institution','pmid','grant_id','grant_amount_usd','description','tags']

for path in ['events.csv', '../v2/events.csv']:
    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=FIELDS, quoting=csv.QUOTE_ALL)
        w.writeheader()
        w.writerows(EVENTS)

print(f"Written {len(EVENTS)} rows to v3/events.csv and v2/events.csv")
